build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - nikola build
    - mkdir deploy
    - cp -r output/ deploy/$CI_BRANCH


deploy:

  rsync:
    host: hera.physchem.kth.se
    user: bjodah-github-io
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
